repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        exclude: ./(env|venv|virtualenv)
        files: (?x)^.*(\.py)$
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.2
    hooks:
    - id: prettier
      exclude: ./(env|venv|virtualenv)
      files: |
        (?x)^.*(\.css|\.html|\.js)$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: check-json
        files: |
          (?x)^.*(\.json)$
      - id: check-yaml
        files: |
          (?x)^.*(\.yaml|\.yml)$
      - id: end-of-file-fixer
        exclude: |
          (?x)^requirements.*(\.txt)$
      - id: trailing-whitespace
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        exclude: |
          (?x)^.*(\.json|\.txt)$
