---
blank_issues_enabled: false
contact_links:
  - name: General Question
    about: Please ask and answer questions as a discussion thread
    url: https://github.com/lindsaygelle/AWSPhotographer/discussions/categories/q-a
