name: pull_request

on:
  pull_request:
  workflow_dispatch:

jobs:
  lambda_functions:
    defaults:
      run:
        shell: bash
    env:
      DIRECTORY_SRC: "./src"
      DIRECTORY_LAMBDA: $DIRECTORY_SRC/lambda_function
      DIRECTORY_REKOGNITION: $DIRECTORY_LAMBDA/rekognition
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        working_directory:
          - $DIRECTORY_REKOGNITION/detect_faces
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.0
      - run: go get
        working-directory: ${{ matrix.working_directory }}
      - run: go build
        working-directory: ${{ matrix.working_directory }}
      - run: go test ./...
        working-directory: ${{ matrix.working_directory }}

  lint:
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.0

  terraform:
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init
      - run: terraform fmt -check
      - run: terraform plan -input=false
