name: pull_request

on:
  pull_request:
  workflow_dispatch:

jobs:
  lambda_functions:
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lambda_functions:
          - ./src/lambda_function/rekognition/detect_faces
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.0
      - run: |
          make test
        working-directory: ${{ matrix.lambda_functions }}

  lint:
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.0

  terraform:
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: |
          terraform init
      - run: |
          terraform fmt -check
      - run: |
          terraform plan -input=false
