name: "pull_request"

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  lambda_functions:
    defaults:
      run:
        shell: "bash"
    permissions:
      contents: "read"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        lambda_functions:
          - "./src/lambda_function/rekognition/detect_faces"
    steps:
      - uses: "actions/checkout@v3"
      - run: go test main.go
        working-directory: "${{ matrix.lambda_functions }}"
