name: "terraform_documentation"

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  main:
    defaults:
      run:
        shell: "bash"
    permissions:
      contents: "read"
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        modules:
          - "lambda_function"
          - "s3"
        os:
          - "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: "terraform-docs/gh-actions@main"
        with:
          git-push: true
          output-file: "README.md"
          output-method: "inject"
          working-dir: "./modules/${{ matrix.modules }}"
